[project]
name = "learn-scrp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ananya Mengistu", email = "ananyamengisu06@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "apify-client>=3.2.1",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "scrapy>=2.19.0",
    "sqlalchemy>=2.1.1",
    "teleglance>=0.1.1",
]

[project.scripts]
learn-scrp = "learn_scrp:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
